<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fo="http://www.w3.org/1999/XSL/Format">

	<xsl:template match="/">
		<document filename="example.pdf">
			<template pageSize="29.7cm,21cm" leftMargin="2.0cm" rightMargin="2.0cm" topMargin="2.0cm" bottomMargin="2.0cm" title="Report" author="Generated by Open ERP, Fabien Pinckaers" allowSplitting="20">
				<pageTemplate id="first_page">
					<pageGraphics>
						<!--logo-->
						<fill color="black"/>
				        <stroke color="black"/>
				        <setFont name="DejaVu Sans" size="8"/>
				        <drawString x="1.3cm" y="19.5cm"><xsl:value-of select="//header-date"/></drawString>
				        <setFont name="DejaVu Sans Bold" size="10"/>
				        <drawString x="13.8cm" y="19.5cm"><xsl:value-of select="//company"/></drawString>
				        <stroke color="#000000"/>
				        <lines size="8">1.3cm 19.3cm 28.5cm 19.3cm</lines>
					</pageGraphics>

					<frame id="col1" x1="2.0cm" y1="2.5cm" width="24.7cm" height="16cm"/>
				</pageTemplate>
			</template>


			<stylesheet>
				<xsl:if test="report/config/lang='rtl'">
		    	    <xsl:call-template name="rtl_stylesheet"/>
				</xsl:if>
				<xsl:if test="report/config/lang='ltr'">
		    	    <xsl:call-template name="ltr_stylesheet"/>
				</xsl:if>
		    </stylesheet>

			<story>
				<xsl:call-template name="story"/>
			</story>

		</document>
	</xsl:template>

	<!-- stylesheet -->

	<xsl:template name="rtl_stylesheet">
		<paraStyle name="title" fontName="Helvetica-Bold" fontSize="22" alignment="center"/>
		<paraStyle name="test" alignment="right" />
        <paraStyle name="float_right" alignment="right"/>
        <paraStyle name="tbl_heading" alignment="center"/>
		<blockTableStyle id="products">
			<blockValign value="CENTER"/>
			<blockAlignment value="CENTER"/>
			<blockBackground colorName="#D3D3F3" start="0,0" stop="-1,0"/>
			<lineStyle kind="GRID" colorName="#e6e6e6"/>
			<blockTopPadding length="8"/>
			<blockBottomPadding length="4"/>
		</blockTableStyle>
	</xsl:template>

	<xsl:template name="ltr_stylesheet">
		<paraStyle name="title" fontName="Helvetica-Bold" fontSize="22" alignment="center"/>
		<paraStyle name="test" alignment="left" />
        <paraStyle name="float_right" alignment="left"/>
        <paraStyle name="tbl_heading" alignment="center"/>
		<blockTableStyle id="products">
			<blockValign value="CENTER"/>
			<blockAlignment value="CENTER"/>
			<blockBackground colorName="#D3D3F3" start="0,0" stop="-1,0"/>
			<lineStyle kind="GRID" colorName="#e6e6e6"/>
			<blockTopPadding length="8"/>
			<blockBottomPadding length="4"/>
		</blockTableStyle>
	</xsl:template>
		
	<xsl:template name="story">
		<xsl:apply-templates select="report"/>
	</xsl:template>

	<xsl:template match="report">
		<xsl:apply-templates select="config"/>
		<!--<setNextTemplate name="other_pages"/>-->
		<blockTable style="products">
		<xsl:if test="string-length(./config/tableSize)&gt;1">
			<xsl:attribute name="colWidths">
				 <xsl:value-of select="./config/tableSize"/>
			</xsl:attribute>
		</xsl:if>

		<xsl:apply-templates select="header"/>
		<xsl:apply-templates select="lines"/>
		</blockTable>
	</xsl:template>


	<xsl:template match="config">
		<para style="title">
		<xsl:value-of select="report-header"/>
		</para>
		<spacer length="1cm" width="2mm"/>
	</xsl:template>

	<xsl:template match="header">
		<tr>
		<xsl:for-each select="field">
			<td>
			<para style="tbl_heading"><font fontName="Helvetica-Bold" fontSize="9">
			<xsl:value-of select="."/></font>
			</para>
			</td>
		</xsl:for-each>
		</tr>
	</xsl:template>

	<xsl:template match="lines">
		<xsl:apply-templates select="row"/>
	</xsl:template>

	<xsl:template match="row">
		<tr>
		<xsl:apply-templates select="col"/>
		</tr>
	</xsl:template>

	<xsl:template match="col">
		<td>
			<xsl:choose>
				<xsl:when test="@para='yes'">
					<xsl:choose>
						<xsl:when test="@tree='yes'">
							<para style="test">
								<xsl:attribute name="leftIndent"><xsl:value-of select="@space"/></xsl:attribute>
								<font fontName="Helvetica" fontSize="9">
								<xsl:value-of select="."/>
								</font>
							</para>
						</xsl:when>
                       <xsl:when test="@tree='float'">
                           <para style="float_right"><font fontName="Helvetica" fontSize="9">
                               <xsl:value-of select="."/>
                               </font></para>
                       </xsl:when>

						<xsl:otherwise>
							<para style="test">
								<font fontName="Helvetica" fontSize="9">
								<xsl:value-of select="."/>
								</font>
							</para>
						</xsl:otherwise>
					</xsl:choose>
				</xsl:when>
				<xsl:when test="@para='group'">
					<xsl:choose>
						<xsl:when test="@tree='yes'">
							<para>
								<xsl:attribute name="leftIndent"><xsl:value-of select="@space"/></xsl:attribute>
								<font fontName="Helvetica-bold" fontSize="9">
								<xsl:value-of select="."/>
								</font>
							</para>
						</xsl:when>
                       <xsl:when test="@tree='float'">
                           <para style="float_right"><font fontName="Helvetica-bold" fontSize="9" color="black">
                               <xsl:value-of select="."/>
                               </font></para>
                       </xsl:when>
                       <xsl:when test="@tree='undefined'">
                            <para>
                                <xsl:attribute name="leftIndent">
                                    <xsl:value-of select="@space"/>
                                </xsl:attribute>
                                <font fontName="Helvetica-Bold" fontSize="9" color="gray">
                                    <xsl:value-of select="."/>
                                </font>
                            </para>
                       </xsl:when>

						<xsl:otherwise>
							<para style="test">
								<font fontName="Helvetica-bold" fontSize="9" color="black">
								<xsl:value-of select="."/>
								</font>
							</para>
						</xsl:otherwise>
					</xsl:choose>

				</xsl:when>
				<xsl:otherwise>
					<xpre>
						<xsl:value-of select="."/>
					</xpre>
				</xsl:otherwise>
			</xsl:choose>
		</td>
	</xsl:template>
	
</xsl:stylesheet>
